dist: xenial

language: go

env:
  - GO111MODULE=on

go:
  - 1.12.x

git:
  depth: 1

script:
  - "make build"
  - "make test"
  - "make image"

branches:
  only:
    - master

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
